# Autoescalado horizontal: escala de 2 a 6 réplicas según uso de CPU.
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: securetask-api
  namespace: securetask
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: securetask-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
